### ISSUE TITLE
Error in Eclipse preferences window, Jnario option is unusable

### ISSUE THREAD

**Issue by trylks** [sebastianbenz/Jnario#164]
To whoever may be working or will work on this, I hope this helps in the identification and solution of the problem.

Please let me know if any more information would be useful.

The problem arises when clicking on the Jnario part of the tree in the preferences window, either for projects or in the general Eclipse preferences. Everything else in the preferences window seems to work fine.

# Versions:

```
Eclipse DSL Tools

Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600
```

![screenshot 2015-04-23 12 15 56](https://cloud.githubusercontent.com/assets/1286855/7295164/9f6bace2-e9b3-11e4-8546-384d370aadfb.png)

# Error:

```
Unable to create the selected preference page.
Guice configuration errors:

1) No implementation for org.eclipse.ui.plugin.AbstractUIPlugin was bound.
  while locating org.eclipse.ui.plugin.AbstractUIPlugin
    for field at org.eclipse.xtext.ui.preferences.OptionsConfigurationBlock.uiPlugin(Unknown Source)
  while locating org.eclipse.xtext.builder.preferences.BuilderConfigurationBlock
    for field at org.eclipse.xtext.builder.preferences.BuilderPreferencePage.builderConfigurationBlock(Unknown Source)
  while locating org.eclipse.xtext.builder.preferences.BuilderPreferencePage

2) No implementation for org.eclipse.jface.dialogs.IDialogSettings was bound.
  while locating org.eclipse.jface.dialogs.IDialogSettings
    for field at org.eclipse.xtext.ui.preferences.PropertyAndPreferencePage.dialogSettings(Unknown Source)
  while locating org.eclipse.xtext.builder.preferences.BuilderPreferencePage

2 errors
```

**Comment by sebastianbenz** [comment]
The problem is that Jnario is currently incompatible to xtend 2.8.
@borisbrodski is currently porting Jnario to Xbase, which will fix these
kind of problems in the future.

**Comment by atao60** [comment]
Thanks for this great framework.

Have you any idea about a release date for this porting?

**Comment by borisbrodski** [comment]
Unfortunately I can't estimate the amount of the remaining porting work. It works actually already but there are some bugs present. Also the maven build has to be ported.

By the way, it would be really great, if someone could do the maven porting.

**Comment by mrs-imran** [comment]
Any update on the above error as i installed the plugin today and still getting the same exception. Do you have workaround? or any time frame when the fix will be available.
Thanks.

**Comment by borisbrodski** [comment]
Here you will find the newest sources of the ported Jnario.

https://github.com/borisbrodski/Jnario/tree/no_xtend_xtext2.9?files=1

Please, build  “no_xtend_xtext2.9“ branch yourself with

    mvn clean install

It works with the latest Xtext.
